name: Carratt workflow

on:
  push:
    branches: [ “main” ]
  pull_request:
    branches: [ “main” ]

jobs:

  build:
  
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Update repository
    - run: git pull
    - name: Launching run all
    - run: ./Run_Scripts.sh
  
